import { Theme } from '../types';

export const win98: Theme = {
  id: 'win98',
  name: 'Windows 98',
  tokens: {
    color: {
      surface: '#c0c0c0',
      surfaceRaised: '#dfdfdf',
      text: '#000000',
      textMuted: '#808080',
      textInvert: '#ffffff',
      border: '#808080',
      borderStrong: '#000000',
      borderLight: '#dfdfdf',
      borderLightest: '#ffffff',
      borderDark: '#808080',
      borderDarkest: '#000000',
      focusRing: '#000000', // Dotted line in win98 usually
      selectionBg: '#000080',
      selectionText: '#ffffff',
    },
    typography: {
      fontFamily: "'MS Sans Serif', 'Microsoft Sans Serif', 'Segoe UI', sans-serif",
      fontSize: '12px',
      lineHeight: '1.2',
      fontWeight: 400,
    },
    spacing: {
      xs: '2px',
      sm: '4px',
      md: '8px',
      lg: '16px',
      xl: '24px',
    },
    shadow: {
      insetBevel:
        'inset 1px 1px 0 #000000, inset 2px 2px 0 #808080, inset -1px -1px 0 #ffffff, inset -2px -2px 0 #dfdfdf',
      outsetBevel:
        'inset 1px 1px 0 #ffffff, inset 2px 2px 0 #dfdfdf, inset -1px -1px 0 #000000, inset -2px -2px 0 #808080',
      popup: '2px 2px 0 #000000',
    },
    radius: {
      sm: '0px',
      md: '0px',
      lg: '0px',
      round: '9999px',
    },
    gradient: {
      titleBar: 'linear-gradient(90deg, #000080, #1084d0)',
      titleBarInactive: 'linear-gradient(90deg, #808080, #b5b5b5)',
      buttonFace: 'none',
      buttonFaceHover: 'none',
      buttonFaceActive: 'none',
      tabBg: 'none',
      tabBgActive: 'none',
    },
    zIndex: {
      base: 0,
      alwaysTop: 600,
      anchors: 800,
      popups: 1000,
    },
  },
  components: {
    button: {
      face: '#c0c0c0',
      faceHover: '#c0c0c0',
      faceActive: '#c0c0c0',
      text: '#000000',
      borderLight: '#ffffff',
      borderDark: '#808080',
      borderDarker: '#000000',
      border: 'none',
      focusRing: '#000000',
    },
    window: {
      frame: '#c0c0c0',
      titleBarBg: '#000080',
      titleBarText: '#ffffff',
      titleBarBgInactive: '#808080',
      titleBarTextInactive: '#c0c0c0',
      titleBarHeight: '18px',
      closeButtonBg: '#c0c0c0',
      closeButtonBgHover: '#c0c0c0',
      closeButtonBgActive: '#c0c0c0',
    },
    taskbar: {
      bg: '#c0c0c0',
      height: '28px',
      borderLight: '#ffffff',
      borderDark: '#808080',
      itemBg: '#c0c0c0',
      itemBgHover: '#dfdfdf',
      itemBgActive: '#808080',
      itemText: '#000000',
      itemTextActive: '#ffffff',
    },
    startButton: {
      bg: '#c0c0c0',
      bgHover: '#dfdfdf',
      bgActive: '#808080',
      text: '#000000',
      borderLight: '#ffffff',
      borderDark: '#808080',
      borderDarker: '#000000',
    },
  },
  behavior: {
    windowDragMode: 'static',
    windowDefaults: {
      interactionMode: 'static',
      movable: true,
      resizable: false,
      minWidth: 200,
      minHeight: 100,
      activateWholeArea: true,
    },
    startMenuMount: 'bottom',
    docking: {
      zones: [
        {
          id: 'top-left',
          gridColumnStart: 1,
          gridColumnEnd: 2,
          gridRowStart: 1,
          gridRowEnd: 2,
          priority: 4,
        },
        {
          id: 'top',
          gridColumnStart: 2,
          gridColumnEnd: 3,
          gridRowStart: 1,
          gridRowEnd: 2,
          enabled: false,
          priority: 1,
        },
        {
          id: 'top-right',
          gridColumnStart: 3,
          gridColumnEnd: 4,
          gridRowStart: 1,
          gridRowEnd: 2,
          priority: 4,
        },
        {
          id: 'left',
          gridColumnStart: 1,
          gridColumnEnd: 2,
          gridRowStart: 2,
          gridRowEnd: 3,
          priority: 1,
        },
        {
          id: 'right',
          gridColumnStart: 3,
          gridColumnEnd: 4,
          gridRowStart: 2,
          gridRowEnd: 3,
          priority: 1,
        },
        {
          id: 'bottom-left',
          gridColumnStart: 1,
          gridColumnEnd: 2,
          gridRowStart: 3,
          gridRowEnd: 4,
          priority: 4,
        },
        {
          id: 'bottom',
          gridColumnStart: 2,
          gridColumnEnd: 3,
          gridRowStart: 3,
          gridRowEnd: 4,
          priority: 1,
        },
        {
          id: 'bottom-right',
          gridColumnStart: 3,
          gridColumnEnd: 4,
          gridRowStart: 3,
          gridRowEnd: 4,
          priority: 4,
        },
      ],
      policy: {
        thresholdPx: 18,
        mode: 'release',
      },
    },
  },
};
